import React, { useState, useEffect, useRef, useCallback } from "react";

/* ============================================================
   SUDOKU CORE — bitmask solver, generator, validators
   ------------------------------------------------------------
   Correctness guarantees:
   1. Full grids are generated by randomized backtracking and
      verified as valid permutations of 1–9 in all 27 units.
   2. Clue removal only commits if an exhaustive solution count
      (MRV backtracking, early exit at 2) returns exactly 1.
   3. Easy/Medium additionally require the puzzle to be solvable
      using naked + hidden singles only (human-logic gradable).
   4. A post-generation validation suite re-verifies everything
      from scratch and renders a QC report.
   ============================================================ */

// ---------- seeded PRNG (mulberry32) ----------
function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffled(arr, rand) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = (rand() * (i + 1)) | 0;
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ---------- index helpers ----------
const rowOf = (i) => (i / 9) | 0;
const colOf = (i) => i % 9;
const boxOf = (i) => (((i / 9) | 0) / 3 | 0) * 3 + ((i % 9) / 3 | 0);
const ALL = 0x1ff; // bits 0..8 = digits 1..9

function popcount(x) {
  x = x - ((x >> 1) & 0x55555555);
  x = (x & 0x33333333) + ((x >> 2) & 0x33333333);
  return (((x + (x >> 4)) & 0x0f0f0f0f) * 0x01010101) >> 24;
}
const bitToDigit = (bit) => 31 - Math.clz32(bit) + 1;

// 27 units (9 rows, 9 cols, 9 boxes), each a list of 9 cell indices
const UNITS = (() => {
  const u = [];
  for (let r = 0; r < 9; r++) u.push(Array.from({ length: 9 }, (_, c) => r * 9 + c));
  for (let c = 0; c < 9; c++) u.push(Array.from({ length: 9 }, (_, r) => r * 9 + c));
  for (let br = 0; br < 3; br++)
    for (let bc = 0; bc < 3; bc++) {
      const cells = [];
      for (let r = 0; r < 3; r++)
        for (let c = 0; c < 3; c++) cells.push((br * 3 + r) * 9 + (bc * 3 + c));
      u.push(cells);
    }
  return u;
})();

// build row/col/box occupancy masks; returns null on contradiction
function buildMasks(cells) {
  const rows = new Array(9).fill(0);
  const cols = new Array(9).fill(0);
  const boxes = new Array(9).fill(0);
  for (let i = 0; i < 81; i++) {
    const v = cells[i];
    if (!v) continue;
    const bit = 1 << (v - 1);
    const r = rowOf(i), c = colOf(i), b = boxOf(i);
    if ((rows[r] | cols[c] | boxes[b]) & bit) return null;
    rows[r] |= bit; cols[c] |= bit; boxes[b] |= bit;
  }
  return { rows, cols, boxes };
}

/**
 * Exhaustive solution counter with early exit.
 * MRV heuristic: always branch on the empty cell with the
 * fewest candidates. Returns { count: min(actual, limit),
 * solution: first solution found (or null) }.
 */
function countSolutionsEx(cellsIn, limit = 2) {
  const cells = cellsIn.slice();
  const m = buildMasks(cells);
  if (!m) return { count: 0, solution: null };
  const { rows, cols, boxes } = m;
  let count = 0;
  let first = null;

  function dfs() {
    let best = -1, bestMask = 0, bestN = 10;
    for (let i = 0; i < 81; i++) {
      if (cells[i]) continue;
      const mask = ~(rows[rowOf(i)] | cols[colOf(i)] | boxes[boxOf(i)]) & ALL;
      const n = popcount(mask);
      if (n === 0) return;            // dead end
      if (n < bestN) { bestN = n; best = i; bestMask = mask; if (n === 1) break; }
    }
    if (best === -1) {                // grid complete
      count++;
      if (count === 1) first = cells.slice();
      return;
    }
    const r = rowOf(best), c = colOf(best), b = boxOf(best);
    let mask = bestMask;
    while (mask && count < limit) {
      const bit = mask & -mask;
      mask ^= bit;
      cells[best] = bitToDigit(bit);
      rows[r] |= bit; cols[c] |= bit; boxes[b] |= bit;
      dfs();
      cells[best] = 0;
      rows[r] ^= bit; cols[c] ^= bit; boxes[b] ^= bit;
    }
  }
  dfs();
  return { count, solution: first };
}

const countSolutions = (cells, limit = 2) => countSolutionsEx(cells, limit).count;

/**
 * Independent cross-check solver: Knuth's Algorithm X with
 * Dancing Links over the standard sudoku exact-cover matrix
 * (324 constraint columns × 729 candidate rows). Shares no code
 * path with the MRV bitmask solver, so agreement between the two
 * is strong evidence of correctness for both.
 */
function dlxCount(puzzle, limit = 2) {
  if (!buildMasks(puzzle)) return { count: 0, solution: null };
  const NC = 324;
  const maxNodes = 1 + NC + 729 * 4;
  const Lk = new Int32Array(maxNodes), Rk = new Int32Array(maxNodes);
  const Up = new Int32Array(maxNodes), Dn = new Int32Array(maxNodes);
  const Cl = new Int32Array(maxNodes), Sz = new Int32Array(NC + 1);
  const rowID = new Int32Array(maxNodes);
  for (let c = 0; c <= NC; c++) { Up[c] = c; Dn[c] = c; Lk[c] = c - 1; Rk[c] = c + 1; Cl[c] = c; }
  Lk[0] = NC; Rk[NC] = 0;

  let node = NC + 1;
  const rowStart = new Int32Array(729);
  for (let i = 0; i < 81; i++) {
    const r = rowOf(i), c = colOf(i), b = boxOf(i);
    for (let d = 1; d <= 9; d++) {
      const cols = [1 + i, 1 + 81 + r * 9 + d - 1, 1 + 162 + c * 9 + d - 1, 1 + 243 + b * 9 + d - 1];
      const rid = i * 9 + (d - 1);
      rowStart[rid] = node;
      const firstNode = node;
      for (let k = 0; k < 4; k++) {
        const col = cols[k];
        Up[node] = Up[col]; Dn[node] = col; Dn[Up[col]] = node; Up[col] = node;
        Cl[node] = col; Sz[col]++; rowID[node] = rid;
        if (k === 0) { Lk[node] = node; Rk[node] = node; }
        else { Lk[node] = node - 1; Rk[node] = firstNode; Rk[node - 1] = node; Lk[firstNode] = node; }
        node++;
      }
    }
  }

  function cover(col) {
    Rk[Lk[col]] = Rk[col]; Lk[Rk[col]] = Lk[col];
    for (let i2 = Dn[col]; i2 !== col; i2 = Dn[i2])
      for (let j = Rk[i2]; j !== i2; j = Rk[j]) { Up[Dn[j]] = Up[j]; Dn[Up[j]] = Dn[j]; Sz[Cl[j]]--; }
  }
  function uncover(col) {
    for (let i2 = Up[col]; i2 !== col; i2 = Up[i2])
      for (let j = Lk[i2]; j !== i2; j = Lk[j]) { Sz[Cl[j]]++; Up[Dn[j]] = j; Dn[Up[j]] = j; }
    Rk[Lk[col]] = col; Lk[Rk[col]] = col;
  }

  // pre-select rows for the givens (consistency already verified above)
  const work = new Array(81).fill(0);
  for (let i = 0; i < 81; i++) {
    const v = puzzle[i];
    if (!v) continue;
    const n0 = rowStart[i * 9 + (v - 1)];
    let j = n0;
    do { cover(Cl[j]); j = Rk[j]; } while (j !== n0);
    work[i] = v;
  }

  let count = 0;
  let first = null;
  function search() {
    if (Rk[0] === 0) {
      count++;
      if (count === 1) first = work.slice();
      return;
    }
    let col = Rk[0];
    for (let c2 = Rk[0]; c2 !== 0; c2 = Rk[c2]) if (Sz[c2] < Sz[col]) col = c2;
    if (Sz[col] === 0) return;
    cover(col);
    for (let i2 = Dn[col]; i2 !== col && count < limit; i2 = Dn[i2]) {
      const rid = rowID[i2];
      const cell = (rid / 9) | 0;
      for (let j = Rk[i2]; j !== i2; j = Rk[j]) cover(Cl[j]);
      work[cell] = (rid % 9) + 1;
      search();
      work[cell] = 0;
      for (let j = Lk[i2]; j !== i2; j = Lk[j]) uncover(Cl[j]);
    }
    uncover(col);
  }
  search();
  return { count, solution: first };
}

/** Randomized backtracking fill — always succeeds, returns a full valid grid. */
function generateSolution(rand) {
  const cells = new Array(81).fill(0);
  const rows = new Array(9).fill(0);
  const cols = new Array(9).fill(0);
  const boxes = new Array(9).fill(0);

  function dfs() {
    let best = -1, bestMask = 0, bestN = 10;
    for (let i = 0; i < 81; i++) {
      if (cells[i]) continue;
      const mask = ~(rows[rowOf(i)] | cols[colOf(i)] | boxes[boxOf(i)]) & ALL;
      const n = popcount(mask);
      if (n === 0) return false;
      if (n < bestN) { bestN = n; best = i; bestMask = mask; if (n === 1) break; }
    }
    if (best === -1) return true;
    const r = rowOf(best), c = colOf(best), b = boxOf(best);
    const bits = [];
    let mask = bestMask;
    while (mask) { const bit = mask & -mask; mask ^= bit; bits.push(bit); }
    for (const bit of shuffled(bits, rand)) {
      cells[best] = bitToDigit(bit);
      rows[r] |= bit; cols[c] |= bit; boxes[b] |= bit;
      if (dfs()) return true;
      cells[best] = 0;
      rows[r] ^= bit; cols[c] ^= bit; boxes[b] ^= bit;
    }
    return false;
  }
  dfs();
  return cells;
}

/**
 * Constraint-propagation solver restricted to naked singles and
 * hidden singles. Returns the solved grid, or null if those two
 * techniques alone cannot finish (or a contradiction appears).
 * Used to grade whether a puzzle is human-logic solvable.
 */
function solveWithSingles(cellsIn) {
  const cells = cellsIn.slice();
  for (;;) {
    const m = buildMasks(cells);
    if (!m) return null;
    const { rows, cols, boxes } = m;
    let progress = false;
    let complete = true;

    // naked singles
    for (let i = 0; i < 81; i++) {
      if (cells[i]) continue;
      complete = false;
      const mask = ~(rows[rowOf(i)] | cols[colOf(i)] | boxes[boxOf(i)]) & ALL;
      if (mask === 0) return null;
      if (popcount(mask) === 1) {
        cells[i] = bitToDigit(mask);
        const bit = mask;
        rows[rowOf(i)] |= bit; cols[colOf(i)] |= bit; boxes[boxOf(i)] |= bit;
        progress = true;
      }
    }
    if (complete) return cells;

    // hidden singles (per unit, per digit)
    for (const unit of UNITS) {
      let placed = 0;
      for (const i of unit) if (cells[i]) placed |= 1 << (cells[i] - 1);
      let missing = ALL & ~placed;
      while (missing) {
        const bit = missing & -missing;
        missing ^= bit;
        let spot = -1, n = 0;
        for (const i of unit) {
          if (cells[i]) continue;
          const mask = ~(rows[rowOf(i)] | cols[colOf(i)] | boxes[boxOf(i)]) & ALL;
          if (mask & bit) { n++; spot = i; if (n > 1) break; }
        }
        if (n === 0) return null; // digit has nowhere to go
        if (n === 1) {
          cells[spot] = bitToDigit(bit);
          rows[rowOf(spot)] |= bit; cols[colOf(spot)] |= bit; boxes[boxOf(spot)] |= bit;
          progress = true;
        }
      }
    }
    if (!progress) return null; // stuck — needs harder techniques
  }
}

// ---------- difficulty profiles ----------
const DIFFICULTIES = {
  easy:   { label: "Easy",   targetClues: 40, requireSingles: true,  symmetric: true  },
  medium: { label: "Medium", targetClues: 32, requireSingles: true,  symmetric: true  },
  hard:   { label: "Hard",   targetClues: 27, requireSingles: false, symmetric: false },
  expert: { label: "Expert", targetClues: 23, requireSingles: false, symmetric: false },
};

/**
 * Dig holes from a full solution. Every committed removal is
 * re-verified for uniqueness; profile may also demand the puzzle
 * stay solvable with singles only. Returns puzzle + stats.
 */
function digPuzzle(solution, profile, rand) {
  const cells = solution.slice();
  let clues = 81;
  let attempts = 0;

  // removal groups: 180°-rotational pairs (symmetric) or single cells
  let groups;
  if (profile.symmetric) {
    groups = [];
    for (let i = 0; i < 40; i++) groups.push([i, 80 - i]);
    groups.push([40]); // center cell, self-symmetric
  } else {
    groups = Array.from({ length: 81 }, (_, i) => [i]);
  }
  groups = shuffled(groups, rand);

  for (const group of groups) {
    if (clues <= profile.targetClues) break;
    const saved = group.map((i) => cells[i]);
    if (saved.every((v) => v === 0)) continue;
    for (const i of group) cells[i] = 0;
    attempts++;

    let ok = countSolutions(cells, 2) === 1;
    if (ok && profile.requireSingles) ok = solveWithSingles(cells) !== null;

    if (ok) {
      clues -= saved.filter((v) => v !== 0).length;
    } else {
      group.forEach((i, k) => (cells[i] = saved[k]));
    }
  }
  return { puzzle: cells, clues, attempts };
}

// ---------- independent validation suite ----------
function isValidComplete(cells) {
  if (cells.some((v) => v < 1 || v > 9)) return false;
  for (const unit of UNITS) {
    let mask = 0;
    for (const i of unit) mask |= 1 << (cells[i] - 1);
    if (mask !== ALL) return false;
  }
  return true;
}

/**
 * Full validation suite — run on every generated puzzle.
 *   1. structural     solution is a valid permutation in all 27 units
 *   2. cluesSubset    every given matches the stored solution
 *   3. mrvUnique      MRV bitmask solver counts exactly 1 solution
 *   4. solutionMatch  the MRV-found solution equals the stored one
 *   5. dlxUnique      independent DLX exact-cover solver also counts 1
 *   6. solversAgree   MRV and DLX solutions are cell-for-cell identical
 * Plus informational: minimality (every clue individually re-tested
 * for redundancy) and singles-solvability grading.
 */
function fullValidate(puzzle, solution) {
  const structural = isValidComplete(solution);
  const cluesSubset = puzzle.every((v, i) => v === 0 || v === solution[i]);

  const mrv = countSolutionsEx(puzzle, 2);
  const mrvUnique = mrv.count === 1;
  const solutionMatch = mrvUnique && mrv.solution.every((v, i) => v === solution[i]);

  const dlx = dlxCount(puzzle, 2);
  const dlxUnique = dlx.count === 1;
  const solversAgree =
    mrvUnique && dlxUnique && dlx.solution.every((v, i) => v === mrv.solution[i]);

  // minimality: clue i is redundant if uniqueness survives its removal
  let redundantCount = 0;
  const work = puzzle.slice();
  for (let i = 0; i < 81; i++) {
    if (!work[i]) continue;
    const v = work[i];
    work[i] = 0;
    if (countSolutions(work, 2) === 1) redundantCount++;
    work[i] = v;
  }

  const singlesSolvable = solveWithSingles(puzzle) !== null;

  return {
    structural, cluesSubset, mrvUnique, solutionMatch, dlxUnique, solversAgree,
    minimal: redundantCount === 0, redundantCount, singlesSolvable,
  };
}

function checksPass(checks, profile) {
  return (
    checks.structural && checks.cluesSubset &&
    checks.mrvUnique && checks.solutionMatch &&
    checks.dlxUnique && checks.solversAgree &&
    (!profile.requireSingles || checks.singlesSolvable)
  );
}

// ---------- full generation pipeline ----------
function generatePuzzle(difficultyKey, seed) {
  const t0 = performance.now();
  const rand = mulberry32(seed);
  const profile = DIFFICULTIES[difficultyKey];
  const solution = generateSolution(rand);
  const { puzzle, clues, attempts } = digPuzzle(solution, profile, rand);
  const checks = fullValidate(puzzle, solution);
  const timeMs = performance.now() - t0;
  return { puzzle, solution, clues, attempts, checks, timeMs, seed, difficultyKey };
}

/* ============================================================
   UI
   ============================================================ */

const STYLES = `
@import url('https://fonts.googleapis.com/css2?family=Saira+Condensed:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500;600&family=Caveat:wght@500;600;700&display=swap');

.sg-root {
  --paper: #eef1f4;
  --gridline: #c4d2de;
  --ink: #1a232c;
  --blue: #2456a6;
  --blue-deep: #173a6e;
  --red: #c2402a;
  --green: #2e7a4f;
  --muted: #6b7884;
  --panel: #f7f9fa;
  min-height: 100vh;
  background:
    repeating-linear-gradient(0deg, transparent, transparent 23px, rgba(120,150,180,.13) 23px, rgba(120,150,180,.13) 24px),
    repeating-linear-gradient(90deg, transparent, transparent 23px, rgba(120,150,180,.13) 23px, rgba(120,150,180,.13) 24px),
    var(--paper);
  color: var(--ink);
  font-family: 'IBM Plex Mono', monospace;
  padding: 28px 20px 56px;
  box-sizing: border-box;
}
.sg-root *, .sg-root *::before, .sg-root *::after { box-sizing: border-box; }

.sg-header { max-width: 980px; margin: 0 auto 22px; border-bottom: 3px solid var(--ink); padding-bottom: 10px;
  display: flex; align-items: baseline; justify-content: space-between; flex-wrap: wrap; gap: 6px; }
.sg-title { font-family: 'Saira Condensed', sans-serif; font-weight: 700; font-size: 34px;
  letter-spacing: .06em; text-transform: uppercase; margin: 0; line-height: 1; }
.sg-title small { color: var(--blue); }
.sg-sub { font-size: 11px; letter-spacing: .12em; text-transform: uppercase; color: var(--muted); }

.sg-layout { max-width: 980px; margin: 0 auto; display: grid; grid-template-columns: minmax(0,1fr) 320px; gap: 28px; }
@media (max-width: 860px) { .sg-layout { grid-template-columns: 1fr; } }

.sg-board { display: grid; grid-template-columns: repeat(9, 1fr); width: 100%; max-width: 520px;
  border: 3px solid var(--ink); background: #fcfdfe; user-select: none; }
.sg-cell { position: relative; aspect-ratio: 1; display: flex; align-items: center; justify-content: center;
  cursor: pointer;
  border-right: 1px solid var(--gridline); border-bottom: 1px solid var(--gridline);
  transition: background .08s; }
.sg-cell.b-right { border-right: 2px solid var(--ink); }
.sg-cell.b-bottom { border-bottom: 2px solid var(--ink); }
.sg-cell.peer { background: #eaf0f7; }
.sg-cell.same { background: #dde9f6; }
.sg-cell.selected { background: #d3e2f5; box-shadow: inset 0 0 0 2px var(--blue); }
.sg-cell.conflict { background: #f7d9d2; }
.sg-cell.wrong::after { content: ''; position: absolute; inset: 14% auto auto 14%; width: 72%; height: 72%;
  border-bottom: 2.5px solid var(--red); transform: rotate(-45deg) translateY(10px); opacity: .7;
  pointer-events: none; z-index: 3; }
.sg-cell:focus-visible { outline: 3px solid var(--blue); outline-offset: -3px; }

/* colorku discs — value rendered as a colored "marble" */
.sg-disc { width: 66%; height: 66%; border-radius: 50%;
  border: 1.5px solid rgba(0,0,0,.18);
  box-shadow: inset 0 -3px 5px rgba(0,0,0,.22), inset 0 2px 4px rgba(255,255,255,.45);
  pointer-events: none; }
.sg-disc.given { width: 74%; height: 74%;
  box-shadow: inset 0 -3px 5px rgba(0,0,0,.25), inset 0 2px 4px rgba(255,255,255,.45),
    0 0 0 2px rgba(26,35,44,.30); }

.sg-controls { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 14px; max-width: 520px; }
.sg-pad { display: grid; grid-template-columns: repeat(5, 1fr); gap: 6px; margin-top: 14px; max-width: 520px; }
.sg-btn { font-family: 'IBM Plex Mono', monospace; font-size: 13px; font-weight: 600; letter-spacing: .04em;
  padding: 9px 14px; border: 2px solid var(--ink); background: #fcfdfe; color: var(--ink); cursor: pointer;
  transition: background .1s, transform .05s; }
.sg-btn:hover { background: #e8eef5; }
.sg-btn:active { transform: translateY(1px); }
.sg-btn.primary { background: var(--blue-deep); border-color: var(--blue-deep); color: #fff; }
.sg-btn.primary:hover { background: var(--blue); }
.sg-btn:disabled { opacity: .45; cursor: default; }
.sg-btn.on { background: var(--ink); color: #fff; }

/* color pad — a swatch button per value */
.sg-colorbtn { position: relative; padding: 0; aspect-ratio: 1; border: 2px solid var(--ink);
  background: #fcfdfe; display: flex; align-items: center; justify-content: center; cursor: pointer;
  transition: transform .05s; }
.sg-colorbtn:active { transform: translateY(1px); }
.sg-colorbtn:disabled { opacity: .45; cursor: default; }
.sg-colorbtn .sw { width: 72%; height: 72%; border-radius: 50%;
  border: 1.5px solid rgba(0,0,0,.18);
  box-shadow: inset 0 -3px 5px rgba(0,0,0,.22), inset 0 2px 4px rgba(255,255,255,.45); }
.sg-colorbtn .lbl { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);
  font-size: clamp(15px, 3vw, 22px); color: #fff; font-weight: 700; line-height: 1;
  text-shadow: 0 1px 2px rgba(0,0,0,.55), 0 0 3px rgba(0,0,0,.4); pointer-events: none; }
.sg-colorbtn.done .sw { opacity: .28; }
.sg-colorbtn.done .lbl { color: var(--muted); text-shadow: none; }
.sg-erase { aspect-ratio: 1; font-size: 18px; }

/* pencil guesses — hollow rings ("holes"): the color shows only as a rim with
   an empty center, so a guess reads clearly differently from a committed marble.
   A radial mask punches the center out, which also works for the rainbow (9). */
.sg-pencil { display: flex; flex-wrap: wrap; align-items: center; justify-content: center;
  width: 100%; height: 100%; gap: 2px; padding: 8%; box-sizing: border-box; }
.sg-note-disc { border-radius: 50%; opacity: .82; aspect-ratio: 1;
  height: clamp(13px, 2.6vw, 20px); width: auto;
  -webkit-mask: radial-gradient(circle, transparent 0 56%, #000 59%);
  mask: radial-gradient(circle, transparent 0 56%, #000 59%); }
.sg-pencil.single .sg-note-disc { height: clamp(22px, 4.4vw, 34px); opacity: .9; }

.sg-panel { border: 2px solid var(--ink); background: var(--panel); }
.sg-panel + .sg-panel { margin-top: 20px; }
.sg-panel-head { font-family: 'Saira Condensed', sans-serif; font-weight: 600; text-transform: uppercase;
  letter-spacing: .1em; font-size: 15px; padding: 8px 14px; background: var(--ink); color: #fff; }
.sg-panel-body { padding: 14px; }

.sg-diff { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; margin-bottom: 12px; }
.sg-diff .sg-btn.on { background: var(--ink); color: #fff; }

.sg-report { position: relative; }
.sg-row { display: flex; justify-content: space-between; align-items: baseline;
  font-size: 12.5px; padding: 5px 0; border-bottom: 1px dashed var(--gridline); }
.sg-row:last-child { border-bottom: none; }
.sg-row .k { color: var(--muted); letter-spacing: .03em; }
.sg-row .v { font-weight: 600; }
.sg-row .pass { color: var(--green); }
.sg-row .fail { color: var(--red); }
.sg-row .na { color: var(--muted); font-weight: 400; }

.sg-stamp { position: absolute; right: 12px; bottom: 10px; transform: rotate(-9deg);
  font-family: 'Saira Condensed', sans-serif; font-weight: 700; font-size: 19px; letter-spacing: .14em;
  color: var(--green); border: 3px double var(--green); border-radius: 4px; padding: 2px 10px;
  text-transform: uppercase; opacity: .9; pointer-events: none; }
.sg-stamp.bad { color: var(--red); border-color: var(--red); }

.sg-status { margin-top: 12px; font-size: 13px; min-height: 20px; max-width: 520px; }
.sg-status.ok { color: var(--green); font-weight: 600; }
.sg-status.err { color: var(--red); font-weight: 600; }

.sg-checkline { display: inline-flex; align-items: center; gap: 6px; font-size: 12px;
  color: var(--muted); letter-spacing: .03em; cursor: pointer; padding: 9px 4px; }
.sg-checkline input { accent-color: var(--blue-deep); }

@media (prefers-reduced-motion: reduce) { .sg-root * { transition: none !important; } }

/* ---------- print layout ---------- */
.sg-print { display: none; }
@media print {
  .sg-root { display: none !important; }
  .sg-print { display: block; font-family: 'IBM Plex Mono', monospace; color: #000; padding: 0; }
  @page { margin: 1.5cm; }
}
.sgp-head { display: flex; justify-content: space-between; align-items: baseline;
  border-bottom: 3px solid #000; padding-bottom: 6px; margin-bottom: 4mm; }
.sgp-title { font-family: 'Saira Condensed', sans-serif; font-weight: 700; font-size: 20pt;
  letter-spacing: .06em; text-transform: uppercase; margin: 0; }
.sgp-meta { font-size: 9pt; text-align: right; line-height: 1.5; }
.sgp-board { display: grid; grid-template-columns: repeat(9, 1fr); width: 15cm; height: 15cm;
  border: 1mm solid #000; margin: 6mm auto 0; }
.sgp-cell { display: flex; align-items: center; justify-content: center; font-size: 20pt; font-weight: 600;
  border-right: 0.2mm solid #888; border-bottom: 0.2mm solid #888; }
.sgp-cell.b-right { border-right: 0.6mm solid #000; }
.sgp-cell.b-bottom { border-bottom: 0.6mm solid #000; }
.sgp-cell:nth-child(9n) { border-right: none; }
.sgp-foot { text-align: center; font-size: 8pt; color: #444; margin-top: 5mm; letter-spacing: .04em; }
.sgp-key { page-break-before: always; }
.sgp-key .sgp-board { width: 9cm; height: 9cm; }
.sgp-key .sgp-cell { font-size: 11pt; font-weight: 400; }
.sgp-key .sgp-cell.given { font-weight: 700; }
.sgp-key h2 { font-family: 'Saira Condensed', sans-serif; text-transform: uppercase;
  letter-spacing: .08em; font-size: 13pt; text-align: center; margin: 0 0 2mm; }
`;

// colorku: map values 1–9 to nine distinguishable colors
const COLORKU = {
  1: "#d11149", // red
  2: "#f0741f", // orange
  3: "#ffd21f", // yellow
  4: "#3aa655", // green
  5: "#15b5c4", // teal
  6: "#2f5fd0", // blue
  7: "#7a3fb5", // purple
  8: "#d23fa0", // magenta
  9: "#166534", // (fallback) — rendered as a rainbow ball, see RAINBOW below
};
// value 9 is a rainbow "ball": a full-spectrum conic sweep (endpoints meet for a seamless wheel)
const RAINBOW =
  "conic-gradient(from 140deg, #ff3b30, #ff9500, #ffcc00, #34c759, #30c0d8, #2f6bff, #7a3fb5, #ff2d92, #ff3b30)";
const baseFill = (v) => (v === 9 ? RAINBOW : COLORKU[v]);
// glossy "marble" fill: white highlight layered over the base color/sweep
const discBg = (v) =>
  `radial-gradient(circle at 34% 28%, rgba(255,255,255,.55), rgba(255,255,255,0) 46%), ${baseFill(v)}`;

/* ============================================================
   PERSISTENCE — one shared board saved to a Lambda + DynamoDB
   backend (same pattern as the BBQ cook-clock). The backend URL
   is discovered at runtime from /colorku/config.json; if it is
   absent or unreachable the app runs purely local (no save).

   Only { seed, difficultyKey, entries, pencil, revealed } is
   stored — generatePuzzle(difficultyKey, seed) rebuilds the exact
   puzzle on load, so the saved doc stays tiny.
   ============================================================ */
const BOARD_DIFFS = new Set(Object.keys(DIFFICULTIES));

async function discoverBoardUrl() {
  try {
    const r = await fetch("/colorku/config.json", { cache: "no-store" });
    if (!r.ok) return null;
    const j = await r.json();
    return j && typeof j.boardUrl === "string" ? j.boardUrl : null;
  } catch {
    return null;
  }
}

// Stable JSON of just the persisted slice; used both to POST and to dedupe
// saves (so cursor moves / "check entries" don't trigger needless writes).
function serializeBoard(seed, difficultyKey, entries, pencil, revealed) {
  return JSON.stringify({
    seed: seed >>> 0,
    difficultyKey,
    revealed: !!revealed,
    entries: entries.slice(),
    pencil: pencil.map((s) => [...s].sort((a, b) => a - b)),
  });
}

// Validate a doc loaded from the backend; null if it can't be used.
function parseBoardDoc(doc) {
  if (!doc || typeof doc !== "object") return null;
  if (!BOARD_DIFFS.has(doc.difficultyKey)) return null;
  if (!Number.isFinite(doc.seed)) return null;
  if (!Array.isArray(doc.entries) || doc.entries.length !== 81) return null;
  if (!Array.isArray(doc.pencil) || doc.pencil.length !== 81) return null;
  return doc;
}

export default function SudokuGenerator() {
  const [difficulty, setDifficulty] = useState("medium");
  const [game, setGame] = useState(null);          // result of generatePuzzle
  const [entries, setEntries] = useState(null);    // user grid (givens merged in)
  const [selected, setSelected] = useState(-1);
  const [wrongSet, setWrongSet] = useState(new Set());
  const [conflictSet, setConflictSet] = useState(new Set());
  const [pencil, setPencil] = useState(() => Array.from({ length: 81 }, () => new Set()));
  const [pencilMode, setPencilMode] = useState(false);
  const [status, setStatus] = useState({ text: "", kind: "" });
  const [generating, setGenerating] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const [batch, setBatch] = useState(null);
  const [batchRunning, setBatchRunning] = useState(false);
  const [printWithKey, setPrintWithKey] = useState(false);
  const boardRef = useRef(null);

  // persistence: backend URL (null = local-only), a gate so the initial
  // restore doesn't echo back a write, and the last payload we saved.
  const boardUrlRef = useRef(null);
  const hydratedRef = useRef(false);
  const lastSavedRef = useRef("");

  const printPuzzle = () => {
    if (!game) return;
    window.print();
  };

  // Fallback for hosts without a print dialog (e.g. mobile app WebView):
  // build a fully self-contained HTML sheet and download it. Open it in
  // any browser and use the system print / save-as-PDF flow.
  const downloadSheet = () => {
    if (!game) return;
    const serial = game.seed.toString(16).toUpperCase().padStart(8, "0");
    const grid = (cells, mini) => {
      let h = `<div class="board${mini ? " mini" : ""}">`;
      for (let i = 0; i < 81; i++) {
        const cls = [
          "cell",
          mini && game.puzzle[i] !== 0 ? "given" : "",
          colOf(i) % 3 === 2 && colOf(i) !== 8 ? "br" : "",
          rowOf(i) % 3 === 2 && rowOf(i) !== 8 ? "bb" : "",
        ].filter(Boolean).join(" ");
        h += `<div class="${cls}">${cells[i] || ""}</div>`;
      }
      return h + "</div>";
    };
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sudoku ${serial}</title><style>
body{font-family:ui-monospace,Menlo,Consolas,monospace;color:#000;margin:1.2cm;}
.head{display:flex;justify-content:space-between;align-items:baseline;border-bottom:3px solid #000;padding-bottom:6px;}
h1{font-size:18pt;letter-spacing:.06em;text-transform:uppercase;margin:0;}
.meta{font-size:9pt;text-align:right;line-height:1.5;}
.board{display:grid;grid-template-columns:repeat(9,1fr);width:min(15cm,92vw);aspect-ratio:1;border:1mm solid #000;margin:6mm auto 0;}
.cell{display:flex;align-items:center;justify-content:center;font-size:18pt;font-weight:600;border-right:.2mm solid #888;border-bottom:.2mm solid #888;}
.cell.br{border-right:.6mm solid #000;}.cell.bb{border-bottom:.6mm solid #000;}
.cell:nth-child(9n){border-right:none;}
.board.mini{width:min(9cm,60vw);}.board.mini .cell{font-size:10pt;font-weight:400;}
.board.mini .cell.given{font-weight:700;}
.foot{text-align:center;font-size:8pt;color:#444;margin-top:5mm;}
.key{page-break-before:always;margin-top:10mm;}
.key h2{font-size:12pt;text-transform:uppercase;letter-spacing:.08em;text-align:center;}
@media print{@page{margin:1.5cm}body{margin:0}}
</style></head><body>
<div class="head"><h1>Sudoku/Gen</h1><div class="meta">Serial #${serial}<br>${DIFFICULTIES[game.difficultyKey].label} &middot; ${game.clues} clues &middot; ${new Date().toLocaleDateString()}</div></div>
${grid(game.puzzle, false)}
<div class="foot">Uniqueness verified by two independent solvers (MRV backtracking + DLX exact cover)</div>
${printWithKey ? `<div class="key"><h2>Solution key &mdash; #${serial}</h2>${grid(game.solution, true)}<div class="foot">Given clues in bold</div></div>` : ""}
</body></html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `sudoku-${serial}.html`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  };

  const newPuzzle = useCallback((diff) => {
    setGenerating(true);
    setStatus({ text: "", kind: "" });
    // yield to paint before the (fast) synchronous generation
    setTimeout(() => {
      const seed = (Date.now() ^ (Math.random() * 0xffffffff)) >>> 0;
      const g = generatePuzzle(diff, seed);
      setGame(g);
      setEntries(g.puzzle.slice());
      setPencil(Array.from({ length: 81 }, () => new Set()));
      setSelected(-1);
      setWrongSet(new Set());
      setConflictSet(new Set());
      setRevealed(false);
      setGenerating(false);
    }, 30);
  }, []);

  // On mount: discover the backend and restore the saved shared board if one
  // exists, otherwise generate a fresh puzzle. Saves stay gated until this
  // settles so the restore itself doesn't trigger a write.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const url = await discoverBoardUrl();
      if (cancelled) return;
      boardUrlRef.current = url;

      let restored = false;
      if (url) {
        try {
          const r = await fetch(url, { cache: "no-store" });
          if (r.ok) {
            const doc = parseBoardDoc(await r.json());
            if (doc && !cancelled) {
              const g = generatePuzzle(doc.difficultyKey, doc.seed >>> 0);
              // givens are fixed by the regenerated puzzle; user values must
              // stay within 0..9, anything else falls back to empty
              const e = doc.entries.map((v, i) =>
                g.puzzle[i] !== 0 ? g.puzzle[i] : Number.isInteger(v) && v >= 0 && v <= 9 ? v : 0,
              );
              const pen = doc.pencil.map(
                (arr) =>
                  new Set(
                    (Array.isArray(arr) ? arr : []).filter((d) => Number.isInteger(d) && d >= 1 && d <= 9),
                  ),
              );
              setGame(g);
              setDifficulty(doc.difficultyKey);
              setEntries(e);
              setPencil(pen);
              setRevealed(!!doc.revealed);
              setSelected(-1);
              setWrongSet(new Set());
              setConflictSet(new Set());
              // mark this exact state as already-saved so the first save effect is a no-op
              lastSavedRef.current = serializeBoard(g.seed, g.difficultyKey, e, pen, !!doc.revealed);
              restored = true;
            }
          }
        } catch {
          /* unreachable or malformed — fall through to a fresh puzzle */
        }
      }
      if (!cancelled && !restored) newPuzzle("medium");
      if (!cancelled) hydratedRef.current = true;
    })();
    return () => {
      cancelled = true;
    };
  }, [newPuzzle]);

  // Persist the working board (debounced) whenever the saved slice changes.
  // Gated on hydration; deduped via lastSavedRef so only real board changes
  // (placing/erasing colors, pencil notes, reveal, or a newly generated
  // puzzle) write to the backend.
  useEffect(() => {
    if (!hydratedRef.current) return;
    const url = boardUrlRef.current;
    if (!url || !game || !entries) return;
    const payload = serializeBoard(game.seed, game.difficultyKey, entries, pencil, revealed);
    if (payload === lastSavedRef.current) return;
    const t = setTimeout(() => {
      fetch(url, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: payload,
      })
        .then((r) => {
          if (r.ok) lastSavedRef.current = payload;
        })
        .catch(() => {});
    }, 600);
    return () => clearTimeout(t);
  }, [game, entries, pencil, revealed]);

  // Conflicts are NOT shown live — surfacing a duplicate the instant it's
  // placed would turn deduction into "watch for the highlight." They are
  // computed only on demand by checkProgress(), stored in conflictSet.
  const findConflicts = (grid) => {
    const s = new Set();
    if (!grid) return s;
    for (const unit of UNITS) {
      const seen = {};
      for (const i of unit) {
        const v = grid[i];
        if (!v) continue;
        if (seen[v] !== undefined) { s.add(i); s.add(seen[v]); }
        else seen[v] = i;
      }
    }
    return s;
  };

  const setCell = (i, v) => {
    if (!game || game.puzzle[i] !== 0 || revealed) return;
    setEntries((prev) => {
      const next = prev.slice();
      next[i] = v;
      return next;
    });
    // committing (or clearing) a value empties this cell's candidate notes
    setPencil((prev) => {
      if (prev[i].size === 0) return prev;
      const next = prev.slice();
      next[i] = new Set();
      return next;
    });
    setWrongSet((prev) => {
      if (!prev.has(i)) return prev;
      const n = new Set(prev); n.delete(i); return n;
    });
    setConflictSet((prev) => (prev.size ? new Set() : prev));
    setStatus({ text: "", kind: "" });
  };

  // toggle a candidate digit in a cell's notes (only on empty, non-given cells)
  const togglePencil = (i, d) => {
    if (!game || game.puzzle[i] !== 0 || revealed) return;
    if (entries[i] !== 0) return; // can't pencil over a committed value
    setPencil((prev) => {
      const next = prev.slice();
      const s = new Set(next[i]);
      if (d === 0) s.clear();
      else if (s.has(d)) s.delete(d);
      else s.add(d);
      next[i] = s;
      return next;
    });
    setStatus({ text: "", kind: "" });
  };

  // route a digit press to either a final value or a pencil mark
  const inputDigit = (i, d) => {
    if (pencilMode) togglePencil(i, d);
    else setCell(i, d);
  };

  const onKeyDown = (e) => {
    const k = e.key;
    // toggle pencil mode regardless of selection
    if (k === " " || k === "n" || k === "N") { setPencilMode((m) => !m); e.preventDefault(); return; }
    if (selected < 0) return;
    if (k >= "1" && k <= "9") {
      // Shift forces the opposite mode for this one keystroke
      const d = +k;
      if (e.shiftKey ? !pencilMode : pencilMode) togglePencil(selected, d);
      else setCell(selected, d);
      e.preventDefault();
    }
    else if (k === "0" || k === "Backspace" || k === "Delete") { setCell(selected, 0); e.preventDefault(); }
    else if (k === "ArrowUp" && selected >= 9) { setSelected(selected - 9); e.preventDefault(); }
    else if (k === "ArrowDown" && selected < 72) { setSelected(selected + 9); e.preventDefault(); }
    else if (k === "ArrowLeft" && colOf(selected) > 0) { setSelected(selected - 1); e.preventDefault(); }
    else if (k === "ArrowRight" && colOf(selected) < 8) { setSelected(selected + 1); e.preventDefault(); }
  };

  const checkProgress = () => {
    if (!game || !entries) return;
    const wrong = new Set();
    let filled = 0;
    for (let i = 0; i < 81; i++) {
      if (game.puzzle[i] !== 0) continue;
      if (entries[i] !== 0) {
        filled++;
        if (entries[i] !== game.solution[i]) wrong.add(i);
      }
    }
    const conf = findConflicts(entries);
    setWrongSet(wrong);
    setConflictSet(conf);
    const complete = entries.every((v) => v !== 0);
    // Give an unambiguous correct/incorrect verdict on every check.
    if (complete && wrong.size === 0)
      setStatus({ text: "✓ Correct — solved! Every color matches the unique solution.", kind: "ok" });
    else if (complete)
      setStatus({
        text: `✗ Not solved — ${wrong.size} ${wrong.size === 1 ? "color is" : "colors are"} wrong (marked).`,
        kind: "err",
      });
    else if (wrong.size > 0)
      setStatus({
        text: `✗ ${wrong.size} incorrect ${wrong.size === 1 ? "color" : "colors"} so far (marked).`,
        kind: "err",
      });
    else if (conf.size > 0)
      setStatus({ text: "Duplicate colors in a row, column, or box (marked) — none wrong yet.", kind: "err" });
    else if (filled === 0) setStatus({ text: "Nothing to check yet.", kind: "" });
    else setStatus({ text: "✓ Correct so far — no mistakes yet. Keep going.", kind: "ok" });
  };

  const reveal = () => {
    if (!game) return;
    setEntries(game.solution.slice());
    setPencil(Array.from({ length: 81 }, () => new Set()));
    setWrongSet(new Set());
    setConflictSet(new Set());
    setRevealed(true);
    setStatus({ text: "Solution revealed.", kind: "" });
  };

  const reset = () => {
    if (!game) return;
    setEntries(game.puzzle.slice());
    setPencil(Array.from({ length: 81 }, () => new Set()));
    setWrongSet(new Set());
    setConflictSet(new Set());
    setRevealed(false);
    setStatus({ text: "", kind: "" });
  };

  const selVal = selected >= 0 && entries ? entries[selected] : 0;
  // remaining balls per color = 9 − committed placements on the board.
  // entries holds givens + committed entries; pencil guesses live elsewhere and
  // never count here. Clamp at 0 so an over-placement doesn't reveal itself.
  const remaining = (() => {
    const r = [0, 9, 9, 9, 9, 9, 9, 9, 9, 9];
    if (entries) for (const v of entries) if (v) r[v]--;
    for (let d = 1; d <= 9; d++) if (r[d] < 0) r[d] = 0;
    return r;
  })();
  const checks = game?.checks;
  const profile = game ? DIFFICULTIES[game.difficultyKey] : null;
  const allPass = checks && profile && checksPass(checks, profile);

  const runBatch = () => {
    setBatchRunning(true);
    setTimeout(() => {
      const prof = DIFFICULTIES[difficulty];
      const results = [];
      for (let k = 0; k < 20; k++) {
        const seed = (Date.now() ^ ((Math.random() * 0xffffffff) >>> 0) ^ (k * 2654435761)) >>> 0;
        const g = generatePuzzle(difficulty, seed);
        results.push({
          seed,
          clues: g.clues,
          timeMs: g.timeMs,
          pass: checksPass(g.checks, prof),
          minimal: g.checks.minimal,
        });
      }
      setBatch({ difficulty, results });
      setBatchRunning(false);
    }, 30);
  };

  const Check = ({ ok, naText }) =>
    ok === null
      ? <span className="v na">{naText || "—"}</span>
      : <span className={`v ${ok ? "pass" : "fail"}`}>{ok ? "PASS ✓" : "FAIL ✗"}</span>;

  return (
    <>
    <div className="sg-root">
      <style>{STYLES}</style>

      <header className="sg-header">
        <h1 className="sg-title">Sudoku<small>/Gen</small></h1>
        <div className="sg-sub">uniqueness-verified puzzle generator</div>
      </header>

      <div className="sg-layout">
        {/* ---------- board ---------- */}
        <div>
          <div
            className="sg-board"
            ref={boardRef}
            tabIndex={0}
            onKeyDown={onKeyDown}
            role="grid"
            aria-label="Sudoku board"
          >
            {entries &&
              entries.map((v, i) => {
                const given = game.puzzle[i] !== 0;
                const cls = [
                  "sg-cell",
                  given && "given",
                  colOf(i) % 3 === 2 && colOf(i) !== 8 && "b-right",
                  rowOf(i) % 3 === 2 && rowOf(i) !== 8 && "b-bottom",
                  i === selected && "selected",
                  i !== selected && selected >= 0 &&
                    (rowOf(i) === rowOf(selected) || colOf(i) === colOf(selected) || boxOf(i) === boxOf(selected)) &&
                    "peer",
                  i !== selected && selVal !== 0 && v === selVal && "same",
                  conflictSet.has(i) && "conflict",
                  wrongSet.has(i) && "wrong",
                ]
                  .filter(Boolean)
                  .join(" ");
                return (
                  <div
                    key={i}
                    className={cls}
                    role="gridcell"
                    onClick={() => { setSelected(i); boardRef.current?.focus(); }}
                  >
                    {v !== 0
                      ? <span className={`sg-disc ${given ? "given" : ""}`} style={{ background: discBg(v) }} />
                      : pencil[i].size > 0 && (
                          <div className={`sg-pencil ${pencil[i].size === 1 ? "single" : ""}`}>
                            {[...pencil[i]].sort((a, b) => a - b).map((d) => (
                              <span key={d} className="sg-note-disc" style={{ background: baseFill(d) }} />
                            ))}
                          </div>
                        )}
                  </div>
                );
              })}
          </div>

          <div className="sg-pad">
            {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((d) => (
              <button
                key={d}
                className={`sg-colorbtn ${remaining[d] === 0 ? "done" : ""}`}
                onClick={() => inputDigit(selected, d)}
                disabled={selected < 0}
                title={`Color ${d} — ${remaining[d]} left`}
                aria-label={`Color ${d}, ${remaining[d]} remaining`}
              >
                <span className="sw" style={{ background: discBg(d) }} />
                <span className="lbl">{remaining[d]}</span>
              </button>
            ))}
            <button className="sg-colorbtn sg-erase" onClick={() => setCell(selected, 0)} disabled={selected < 0} aria-label="Erase">⌫</button>
          </div>

          <div className="sg-controls">
            <button
              className={`sg-btn ${pencilMode ? "on" : ""}`}
              onClick={() => setPencilMode((m) => !m)}
              disabled={!game || revealed}
              aria-pressed={pencilMode}
              title="Toggle pencil-mark mode (Space). Hold Shift while typing a digit to pencil without switching modes."
            >
              ✏ Notes: {pencilMode ? "ON" : "OFF"}
            </button>
            <button className="sg-btn" onClick={checkProgress} disabled={!game || revealed}>Check entries</button>
            <button className="sg-btn" onClick={reset} disabled={!game}>Reset board</button>
            <button className="sg-btn" onClick={reveal} disabled={!game || revealed}>Reveal solution</button>
            <button className="sg-btn" onClick={printPuzzle} disabled={!game}>Print</button>
            <button className="sg-btn" onClick={downloadSheet} disabled={!game}>Download sheet</button>
            <label className="sg-checkline">
              <input
                type="checkbox"
                checked={printWithKey}
                onChange={(e) => setPrintWithKey(e.target.checked)}
              />
              with solution key
            </label>
          </div>

          <div className={`sg-status ${status.kind}`}>{status.text}</div>
        </div>

        {/* ---------- generator + QC ---------- */}
        <div>
          <div className="sg-panel">
            <div className="sg-panel-head">Generator</div>
            <div className="sg-panel-body">
              <div className="sg-diff">
                {Object.entries(DIFFICULTIES).map(([key, d]) => (
                  <button
                    key={key}
                    className={`sg-btn ${difficulty === key ? "on" : ""}`}
                    onClick={() => setDifficulty(key)}
                  >
                    {d.label}
                  </button>
                ))}
              </div>
              <button
                className="sg-btn primary"
                style={{ width: "100%" }}
                onClick={() => newPuzzle(difficulty)}
                disabled={generating}
              >
                {generating ? "Generating…" : "Generate puzzle"}
              </button>
            </div>
          </div>

          {game && (
            <div className="sg-panel sg-report">
              <div className="sg-panel-head">Validation report</div>
              <div className="sg-panel-body" style={{ paddingBottom: 52 }}>
                <div className="sg-row"><span className="k">Serial</span><span className="v">#{game.seed.toString(16).toUpperCase().padStart(8, "0")}</span></div>
                <div className="sg-row"><span className="k">Difficulty</span><span className="v">{DIFFICULTIES[game.difficultyKey].label}</span></div>
                <div className="sg-row"><span className="k">Clues</span><span className="v">{game.clues} / 81</span></div>
                <div className="sg-row"><span className="k">Removal trials</span><span className="v">{game.attempts}</span></div>
                <div className="sg-row"><span className="k">Gen + QA time</span><span className="v">{game.timeMs.toFixed(1)} ms</span></div>
                <div className="sg-row"><span className="k">Units valid (27/27)</span><Check ok={checks.structural} /></div>
                <div className="sg-row"><span className="k">Clues ⊂ solution</span><Check ok={checks.cluesSubset} /></div>
                <div className="sg-row"><span className="k">MRV: 1 solution</span><Check ok={checks.mrvUnique} /></div>
                <div className="sg-row"><span className="k">MRV = stored sol.</span><Check ok={checks.solutionMatch} /></div>
                <div className="sg-row"><span className="k">DLX: 1 solution</span><Check ok={checks.dlxUnique} /></div>
                <div className="sg-row"><span className="k">DLX = MRV</span><Check ok={checks.solversAgree} /></div>
                <div className="sg-row">
                  <span className="k">Minimal puzzle</span>
                  <span className="v na">{checks.minimal ? "yes — irreducible" : `no — ${checks.redundantCount} redundant`}</span>
                </div>
                <div className="sg-row">
                  <span className="k">Singles-solvable</span>
                  {profile.requireSingles
                    ? <Check ok={checks.singlesSolvable} />
                    : <span className="v na">{checks.singlesSolvable ? "yes" : "no (advanced logic)"}</span>}
                </div>
                <div className={`sg-stamp ${allPass ? "" : "bad"}`}>{allPass ? "Validated" : "Rejected"}</div>
              </div>
            </div>
          )}

          <div className="sg-panel">
            <div className="sg-panel-head">Batch QA</div>
            <div className="sg-panel-body">
              <button
                className="sg-btn"
                style={{ width: "100%" }}
                onClick={runBatch}
                disabled={batchRunning}
              >
                {batchRunning ? "Running 20× full suite…" : `Run 20 × ${DIFFICULTIES[difficulty].label}`}
              </button>
              {batch && (() => {
                const r = batch.results;
                const passed = r.filter((x) => x.pass).length;
                const minimals = r.filter((x) => x.minimal).length;
                const clueMin = Math.min(...r.map((x) => x.clues));
                const clueMax = Math.max(...r.map((x) => x.clues));
                const avgMs = r.reduce((a, x) => a + x.timeMs, 0) / r.length;
                return (
                  <div style={{ marginTop: 12 }}>
                    <div className="sg-row">
                      <span className="k">Result</span>
                      <span className={`v ${passed === r.length ? "pass" : "fail"}`}>
                        {passed}/{r.length} {passed === r.length ? "PASS ✓" : "FAIL ✗"}
                      </span>
                    </div>
                    <div className="sg-row"><span className="k">Difficulty</span><span className="v">{DIFFICULTIES[batch.difficulty].label}</span></div>
                    <div className="sg-row"><span className="k">Clue range</span><span className="v">{clueMin}–{clueMax}</span></div>
                    <div className="sg-row"><span className="k">Minimal puzzles</span><span className="v">{minimals}/{r.length}</span></div>
                    <div className="sg-row"><span className="k">Avg gen + QA</span><span className="v">{avgMs.toFixed(1)} ms</span></div>
                    <div style={{ display: "flex", gap: 4, flexWrap: "wrap", marginTop: 10 }} aria-label="Per-puzzle pass indicators">
                      {r.map((x, i) => (
                        <span
                          key={i}
                          title={`#${x.seed.toString(16).toUpperCase()} — ${x.clues} clues, ${x.timeMs.toFixed(0)} ms`}
                          style={{
                            width: 14, height: 14, display: "inline-block",
                            background: x.pass ? "var(--green)" : "var(--red)",
                            border: "1px solid var(--ink)",
                          }}
                        />
                      ))}
                    </div>
                  </div>
                );
              })()}
            </div>
          </div>
        </div>
      </div>
    </div>

    {/* ---------- print-only layout ---------- */}
    {game && (
      <div className="sg-print" aria-hidden="true">
        <div className="sgp-head">
          <h1 className="sgp-title">Sudoku/Gen</h1>
          <div className="sgp-meta">
            Serial #{game.seed.toString(16).toUpperCase().padStart(8, "0")}<br />
            {DIFFICULTIES[game.difficultyKey].label} · {game.clues} clues · {new Date().toLocaleDateString()}
          </div>
        </div>
        <div className="sgp-board">
          {game.puzzle.map((v, i) => (
            <div
              key={i}
              className={[
                "sgp-cell",
                colOf(i) % 3 === 2 && colOf(i) !== 8 && "b-right",
                rowOf(i) % 3 === 2 && rowOf(i) !== 8 && "b-bottom",
              ].filter(Boolean).join(" ")}
            >
              {v !== 0 ? v : ""}
            </div>
          ))}
        </div>
        <div className="sgp-foot">
          Uniqueness verified by two independent solvers (MRV backtracking + DLX exact cover)
        </div>
        {printWithKey && (
          <div className="sgp-key">
            <h2>Solution key — #{game.seed.toString(16).toUpperCase().padStart(8, "0")}</h2>
            <div className="sgp-board">
              {game.solution.map((v, i) => (
                <div
                  key={i}
                  className={[
                    "sgp-cell",
                    game.puzzle[i] !== 0 && "given",
                    colOf(i) % 3 === 2 && colOf(i) !== 8 && "b-right",
                    rowOf(i) % 3 === 2 && rowOf(i) !== 8 && "b-bottom",
                  ].filter(Boolean).join(" ")}
                >
                  {v}
                </div>
              ))}
            </div>
            <div className="sgp-foot">Given clues in bold</div>
          </div>
        )}
      </div>
    )}
    </>
  );
}
